name: advanced_date_formatter
description: "A advanced date formatter for flutter"
version: 1.0.1
repository: https://github.com/berkkebapci/advanced_date_formatter
homepage:
license: MIT

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.20.1
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
