name: advanced_date_formatter
description: "A advanced date formatter for flutter"
version: 0.0.1
author: "berkkebapci berkkebapci@hotmail.com"
homepage:
license: MIT

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
